FROM maven:3-openjdk-14 AS java
COPY . .
ENV LINUX_JMODS /usr/local/openjdk-14/jmods/
RUN mvn package -DskipTests -pl swiss-wowbagger-jdk-server -am

FROM bitnami/minideb
RUN echo 'deb http://ftp.de.debian.org/debian jessie main non-free' >> /etc/apt/sources.list
RUN apt-get update && apt-get -y install mbrola
COPY --from=java swiss-wowbagger-jdk-server/target/jlink /run
EXPOSE 7125
CMD /run/bin/wowbagger
